CREATE DATABASE IF NOT EXISTS monopoli CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE monopoli;

CREATE TABLE IF NOT EXISTS Usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    rut VARCHAR(20) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    fecha_creacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS IndicadorEconomico (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    fecha DATE NOT NULL,
    valor DECIMAL(18,6) NOT NULL,
    fuente VARCHAR(100) NOT NULL,
    fecha_consulta DATETIME NOT NULL,
    usuario VARCHAR(50) NOT NULL,
    creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
